[database]
mongodb = "mongodb://root:CHANGE_MONGO_PASSWORD@mongodb:27017/revolt?authSource=admin"
redis = "redis://redis:6379/"

[rabbit]
host = "rabbitmq"

[hosts]
app = "https://voxithub.ru"
api = "https://voxithub.ru/api"
events = "wss://voxithub.ru/ws"
autumn = "https://voxithub.ru/autumn"
january = "https://voxithub.ru/january"

[hosts.livekit]
worldwide = "wss://voxithub.ru/livekit"

[api]
cors_allowed_origins = [
    "https://voxithub.ru",
    "tauri://localhost"
]

# Disable email verification
[api.smtp]
host = ""

[api.livekit.nodes.worldwide]
url = "http://livekit:7880"
lat = 0.0
lon = 0.0
key = "devkey"
secret = "secret"

[files.s3]
endpoint = "http://minio:9000"
region = "minio"
access_key_id = "minioautumn"
secret_access_key = "minioautumn"
default_bucket = "revolt-uploads"
