[database]
mongodb = "mongodb://root:mongopass123@ghost-chat-mongodb:27017"
redis = "redis://ghost-chat-redis:6379/"

[rabbit]
host = "ghost-chat-rabbitmq"

[files.s3]
endpoint = "http://ghost-chat-minio:9000"
region = "minio"
access_key_id = "minioautumn"
secret_access_key = "minioautumn"
default_bucket = "revolt-uploads"

[hosts]
app = "http://localhost:5173"
api = "http://localhost:14702"
events = "ws://localhost:14703"
autumn = "http://localhost:14704"
january = "http://localhost:14705"

[hosts.livekit]
worldwide = "ws://localhost:7880"

[api.smtp]
host = ""

[api]
cors_allowed_origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:1420",
    "tauri://localhost"
]

[api.livekit.nodes.worldwide]
url = "http://ghost-chat-livekit:7880"
lat = 0.0
lon = 0.0
key = "worldwide_key"
secret = "ZjCofRlfm6GGtjlifmNpCDkcQbEIIVC0"
